// Mock of ../reportsApi.js (docs/api-contract.md §14). Holds the same Kelani
// basin floods history the server's Uc04Seeder seeds - HA-0001 to HA-0014,
// the ten shelters' occupancy with its 14-15 Jun gap, and four organisations'
// daily distributions - and compiles a report from it the way the server's
// four report sections do: the same inclusion rules, Sri Lanka days, daily
// peaks, gaps (step 10) and summary figures. Delivery records aren't kept one
// per citizen here: each send reaches the registered citizens of the districts
// its alert covers (./areaFixtures.js), with the seeder's outcome shares (1 in
// 17 citizens never reached, then a share failing per channel), so citizens
// reached comes out at about 94%, as seeded.
//
// It rejects as the server does: shape errors, an unknown event (404), a range
// or district outside the event (E1, 400), and every requested section empty
// (E2, 404 NO_DATA_FOR_SELECTION - e.g. occupancy only, 14-15 Jun). Refine
// (A1) compiles a stored report's selection again with the filters, honoured
// per section as on the server, and stores the result as a new report.
// `mockControls.failNext` fakes what can't be clicked into. Generated reports
// live in this module's memory, so reloading the page forgets them.

import { DEMO_USERS } from '../../constants/demoUsers';
import { ROLES } from '../../constants/roles';
import { DISTRICTS, RIVER_BASINS, citizensIn, expandToDistrictIds } from './areaFixtures';

const MIN_DELAY_MS = 300;
const MAX_DELAY_MS = 800;
const RECENT_LIMIT = 20;
const DAY_MS = 24 * 60 * 60 * 1000;
// Sri Lanka keeps UTC+05:30 all year (§14.1).
const OFFSET_MS = (5 * 60 + 30) * 60 * 1000;

// Report order (§14.2), with each section's gap reason.
const GAP_REASONS = {
  alertTimeline: 'No alert records',
  citizensReached: 'No delivery records',
  occupancyOverTime: 'No occupancy records',
  resourceDistribution: 'No distribution records',
};
const SECTION_KEYS = Object.keys(GAP_REASONS);
const CHANNELS = ['PUSH', 'SMS', 'AUDIBLE'];
const SUPPLY_TYPES = ['FOOD', 'WATER', 'MEDICINE', 'BLANKETS', 'HYGIENE_KITS'];

const districtNamed = (name) => DISTRICTS.find((item) => item.name === name);
const nameRef = ({ id, name }) => ({ id, name });

// The two events HazardEventSeeder seeds (§8.1). Only the closed one is listed.
const EVENTS = [
  {
    id: '66f7c1a2b3c4d5e6f7a8b9c1',
    name: 'Flood – Gampaha District',
    hazardType: 'FLOOD',
    status: 'ACTIVE',
    startDate: '2026-09-25T00:00:00.000Z',
    endDate: null,
    districts: [nameRef(districtNamed('Gampaha'))],
    createdAt: '2026-09-28T08:00:00.000Z',
    updatedAt: '2026-09-28T08:00:00.000Z',
  },
  {
    id: '66f7c1a2b3c4d5e6f7a8b9c2',
    name: 'Kelani basin floods',
    hazardType: 'FLOOD',
    status: 'CLOSED',
    startDate: '2026-06-08T00:00:00.000Z',
    endDate: '2026-06-20T00:00:00.000Z',
    districts: ['Colombo', 'Gampaha', 'Kalutara'].map((name) => nameRef(districtNamed(name))),
    createdAt: '2026-09-28T08:00:00.000Z',
    updatedAt: '2026-09-28T08:00:00.000Z',
  },
];
const KELANI = EVENTS[1];

// The organisations the Kelani distributions came from, with the ids the
// coordination mock gives them.
const ORGANISATIONS = {
  adra: { id: '66f7c1a2b3c4d5e6f7a8b9d1', name: 'ADRA', type: 'NGO' },
  dmc: { id: '66f7c1a2b3c4d5e6f7a8b9d3', name: 'Government/DMC', type: 'GOVERNMENT' },
  redCross: { id: '66f7c1a2b3c4d5e6f7a8b9d4', name: 'Red Cross Sri Lanka', type: 'NGO' },
  unicef: { id: '66f7c1a2b3c4d5e6f7a8b9d7', name: 'UNICEF Sri Lanka', type: 'DONOR' },
};

// Every organisation OrganisationSeeder seeds (§10.1), by name: the
// organisation filter's choices.
const ALL_ORGANISATIONS = [
  { ...ORGANISATIONS.adra, contactEmail: null },
  { id: '66f7c1a2b3c4d5e6f7a8b9d2', name: 'Fire Service', type: 'GOVERNMENT', contactEmail: null },
  { ...ORGANISATIONS.dmc, contactEmail: null },
  { ...ORGANISATIONS.redCross, contactEmail: 'contact@redcross.lk.example.test' },
  { id: '66f7c1a2b3c4d5e6f7a8b9d5', name: 'SL Army', type: 'ARMED_FORCES', contactEmail: null },
  { id: '66f7c1a2b3c4d5e6f7a8b9d6', name: 'Sri Lanka Police', type: 'POLICE', contactEmail: null },
  { ...ORGANISATIONS.unicef, contactEmail: 'contact@unicef.example.test' },
];

// Reports are generated by the demo DMC officer, with the id the auth mock
// gives them; the signed-in officer isn't known here.
const officerIndex = DEMO_USERS.findIndex(({ role }) => role === ROLES.DMC_OFFICER);
const OFFICER = {
  id: `64f1a2b3c4d5e6f7a8b9c0d${officerIndex + 1}`,
  name: DEMO_USERS[officerIndex]?.name ?? 'Demo Officer',
};

// "14 07:00" -> that time on 14 Jun 2026 in Sri Lanka, as an ISO instant.
const june = (dayAndTime) => {
  const [day, time] = dayAndTime.split(' ');
  return new Date(`2026-06-${day}T${time}:00.000+05:30`).toISOString();
};

// --- The Kelani history, as Uc04Seeder seeds it ---

// Issued, maybe updated, then cleared: each a version of its own.
const ALERTS = [
  ['HA-0001', 'FLOOD', 'SEVERE', ['RiverBasin:Kelani'], '08 06:30', ['10 09:00'], '18 17:00'],
  ['HA-0002', 'FLOOD', 'MEDIUM', ['District:Kalutara'], '08 14:00', [], '12 10:00'],
  ['HA-0003', 'FLOOD', 'HIGH', ['District:Colombo'], '09 07:15', ['11 08:00'], '17 12:00'],
  ['HA-0004', 'LANDSLIDE', 'HIGH', ['District:Kalutara'], '09 16:40', [], '13 09:30'],
  ['HA-0005', 'FLOOD', 'SEVERE', ['District:Gampaha'], '10 05:50', [], '19 08:00'],
  ['HA-0006', 'FLOOD', 'MEDIUM', ['District:Colombo'], '11 13:20', [], '14 11:00'],
  ['HA-0007', 'FLOOD', 'HIGH', ['District:Gampaha'], '12 06:10', ['13 15:00'], '16 10:30'],
  ['HA-0008', 'LANDSLIDE', 'MEDIUM', ['District:Kalutara'], '13 18:00', [], '15 09:00'],
  ['HA-0009', 'FLOOD', 'HIGH', ['RiverBasin:Kelani'], '14 07:00', [], '20 10:00'],
  ['HA-0010', 'FLOOD', 'HIGH', ['District:Kalutara'], '15 06:45', [], '19 14:00'],
  ['HA-0011', 'FLOOD', 'LOW', ['District:Colombo'], '16 09:00', [], '18 09:00'],
  ['HA-0012', 'FLOOD', 'MEDIUM', ['District:Gampaha'], '17 08:30', [], '20 12:00'],
  ['HA-0013', 'FLOOD', 'LOW', ['District:Kalutara'], '18 10:00', [], '20 15:00'],
  ['HA-0014', 'FLOOD', 'MEDIUM', ['District:Colombo'], '19 07:30', [], '20 16:00'],
].map(([referenceNo, hazardType, severity, targets, issued, updates, allClear], index) => {
  const scope = targets.map((target) => {
    const [kind, name] = target.split(':');
    const area = (kind === 'RiverBasin' ? RIVER_BASINS : DISTRICTS).find(
      (item) => item.name === name,
    );
    return { kind, area };
  });
  return {
    id: `66fb2c3d4e5f6a7b8c9d0e${String(index + 1).padStart(2, '0')}`,
    referenceNo,
    hazardType,
    severity,
    event: KELANI.id,
    areas: scope.map(({ kind, area }) => ({ kind, id: area.id, name: area.name })),
    districtIds: expandToDistrictIds(scope),
    history: [
      { status: 'BROADCAST', at: issued },
      ...updates.map((at) => ({ status: 'UPDATED', at })),
      { status: 'CANCELLED', at: allClear },
    ].map((change, version) => ({ ...change, version: version + 1, at: june(change.at) })),
  };
});

// `peak` is each shelter's count at 14:00 on 12 Jun: they total 4,120.
const SHELTER_PEAKS = {
  Colombo: [760, 560, 470],
  Gampaha: [480, 390, 290, 330, 240],
  Kalutara: [350, 250],
};

// How full the shelters were each day, as a share of their peak. 14 and 15
// Jun are missing on purpose: no occupancy was recorded while offline.
const OCCUPANCY_LEVELS = [
  ['08', 0.25],
  ['09', 0.45],
  ['10', 0.7],
  ['11', 0.85],
  ['12', 1],
  ['13', 0.9],
  ['16', 0.6],
  ['17', 0.45],
  ['18', 0.3],
  ['19', 0.15],
  ['20', 0.05],
];

// Three updates a day; the afternoon one is the day's highest.
const OCCUPANCY_UPDATES = [
  ['08:00', 0.9],
  ['14:00', 1],
  ['20:00', 0.95],
];

const OCCUPANCY_RECORDS = Object.entries(SHELTER_PEAKS).flatMap(([districtName, peaks]) =>
  peaks.flatMap((peak, shelterIndex) =>
    OCCUPANCY_LEVELS.flatMap(([day, level]) =>
      OCCUPANCY_UPDATES.map(([time, share]) => ({
        shelter: `${districtName}-${shelterIndex}`,
        district: districtNamed(districtName).id,
        occupants: Math.round(peak * level * share),
        recordedAt: june(`${day} ${time}`),
      })),
    ),
  ),
);

// One distribution a day per organisation and district: daily base x
// district weight x day level, 18,676 items in all.
const SUPPLIES = [
  { organisation: ORGANISATIONS.redCross, supplyType: 'WATER', base: 15 },
  { organisation: ORGANISATIONS.dmc, supplyType: 'FOOD', base: 9 },
  { organisation: ORGANISATIONS.adra, supplyType: 'BLANKETS', base: 3 },
  { organisation: ORGANISATIONS.unicef, supplyType: 'HYGIENE_KITS', base: 2 },
];
const DISTRICT_WEIGHTS = { Colombo: 6, Gampaha: 5, Kalutara: 3 };
const DISTRIBUTION_LEVELS = [2, 3, 4, 5, 5, 5, 4, 4, 4, 3, 3, 2, 2];

const DISTRIBUTIONS = Object.entries(DISTRICT_WEIGHTS).flatMap(([districtName, weight]) =>
  SUPPLIES.flatMap((supply, supplyIndex) =>
    DISTRIBUTION_LEVELS.map((level, dayIndex) => ({
      district: districtNamed(districtName).id,
      supplyType: supply.supplyType,
      organisation: supply.organisation,
      quantity: supply.base * weight * level,
      distributedAt: june(`${String(8 + dayIndex).padStart(2, '0')} ${10 + supplyIndex}:15`),
    })),
  ),
);

const reports = new Map();
let nextReport = 1;
let pendingFailure = null;

function delay() {
  const ms = Math.floor(Math.random() * (MAX_DELAY_MS - MIN_DELAY_MS + 1)) + MIN_DELAY_MS;
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function apiError(status, code, message, errors) {
  const error = new Error(message);
  error.response = {
    status,
    data: {
      success: false,
      error: errors ? { code, message, errors } : { code, message },
    },
  };
  return error;
}

const validationError = (errors) =>
  apiError(400, 'VALIDATION_ERROR', 'Request validation failed.', errors);

// What axios rejects with when the request never got a response.
function networkError() {
  const error = new Error('Network Error');
  error.code = 'ERR_NETWORK';
  return error;
}

// Fakes the next call's failure, then goes back to normal. A faked 409 is
// kept for the next generate, the only call that can meet it.
function takeFailure({ generating = false } = {}) {
  const failure = pendingFailure;
  if (failure === 'notClosed' && !generating) return;
  pendingFailure = null;
  if (failure === 'network') throw networkError();
  if (failure === 'server') {
    throw apiError(500, 'INTERNAL_ERROR', 'Something went wrong. Please try again.');
  }
  if (failure === 'notClosed') {
    throw apiError(
      409,
      'EVENT_NOT_CLOSED',
      'A report can only be generated for a CLOSED event – current status: ACTIVE',
    );
  }
}

// --- Days (§14.1) ---

const dayOf = (instant) => new Date(Date.parse(instant) + OFFSET_MS).toISOString().slice(0, 10);

function isDay(value) {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const time = Date.parse(`${value}T00:00:00.000Z`);
  return !Number.isNaN(time) && new Date(time).toISOString().slice(0, 10) === value;
}

function daysBetween(from, to) {
  const days = [];
  for (let time = Date.parse(from); time <= Date.parse(to); time += DAY_MS) {
    days.push(new Date(time).toISOString().slice(0, 10));
  }
  return days;
}

const isId = (value) => typeof value === 'string' && /^[0-9a-f]{24}$/i.test(value);

// --- Validation (E1, §14.3), in the server's order ---

// The request's shape, as the server's Joi schema words it.
function shapeErrors({ eventId, from, to, districtIds, sections }) {
  const errors = [];
  if (eventId === undefined) errors.push({ field: 'eventId', message: 'eventId is required' });
  else if (!isId(eventId)) errors.push({ field: 'eventId', message: 'must be a valid id' });

  [
    ['from', from],
    ['to', to],
  ].forEach(([field, value]) => {
    if (value === undefined) errors.push({ field, message: `${field} is required` });
    else if (!isDay(value)) errors.push({ field, message: 'must be a date as YYYY-MM-DD' });
  });

  const listErrors = (field, list, { what, isValid, invalidMessage }) => {
    if (list === undefined) return errors.push({ field, message: `${field} is required` });
    if (!Array.isArray(list)) return errors.push({ field, message: `${field} must be an array` });
    if (list.length === 0)
      return errors.push({ field, message: `must select at least one ${what}` });
    return list.forEach((item, index) => {
      if (!isValid(item)) {
        errors.push({ field: `${field}.${index}`, message: invalidMessage(index) });
      } else if (list.indexOf(item) !== index) {
        errors.push({
          field: `${field}.${index}`,
          message: `${field}[${index}] contains a duplicate value`,
        });
      }
    });
  };
  listErrors('districtIds', districtIds, {
    what: 'district',
    isValid: isId,
    invalidMessage: () => 'must be a valid id',
  });
  listErrors('sections', sections, {
    what: 'section',
    isValid: (key) => SECTION_KEYS.includes(key),
    invalidMessage: (index) => `sections[${index}] must be one of [${SECTION_KEYS.join(', ')}]`,
  });
  return errors;
}

// The range and districts against the closed event (DMS-159).
function parameterErrors(event, { from, to, districtIds }) {
  const start = dayOf(event.startDate);
  const end = dayOf(event.endDate);
  const errors = [];
  if (from > to) {
    errors.push({ field: 'from', message: 'must not be after to' });
  } else if (from < start) {
    errors.push({ field: 'from', message: `must be on or after the event start date ${start}` });
  }
  if (to > end) {
    errors.push({ field: 'to', message: `must be on or before the event end date ${end}` });
  }
  const affected = new Set(event.districts.map(({ id }) => id));
  if (districtIds.some((id) => !affected.has(id))) {
    errors.push({ field: 'districtIds', message: 'must be a district the event affected' });
  }
  return errors;
}

// --- The four sections (steps 6-9), each { result, recordDays, summary } ---

// Issued alerts linked to this event or to none, covering a selected
// district, with at least one status change inside the range.
function alertsFor(ctx) {
  return ALERTS.filter(
    (alert) =>
      (alert.event === ctx.event.id || alert.event === null) &&
      alert.districtIds.some((id) => ctx.districtIds.includes(id)) &&
      (ctx.hazardType === null || alert.hazardType === ctx.hazardType) &&
      alert.history.some((change) => ctx.inRange(change.at)),
  );
}

function compileAlertTimeline(ctx) {
  const entries = alertsFor(ctx)
    .flatMap((alert) =>
      alert.history
        .filter((change) => ctx.inRange(change.at))
        .map((change) => ({
          at: change.at,
          date: dayOf(change.at),
          alert: { id: alert.id, referenceNo: alert.referenceNo },
          status: change.status,
          version: change.version,
          hazardType: alert.hazardType,
          severity: alert.severity,
          areas: alert.areas,
        })),
    )
    .sort(
      (a, b) =>
        a.at.localeCompare(b.at) ||
        a.alert.referenceNo.localeCompare(b.alert.referenceNo) ||
        a.version - b.version,
    );

  const perDay = new Map();
  entries.forEach((entry) => perDay.set(entry.date, (perDay.get(entry.date) ?? 0) + 1));
  const alerts = new Set(entries.map((entry) => entry.alert.id)).size;
  return {
    result: {
      alerts,
      entries,
      days: ctx.days.map((date) => ({ date, entries: perDay.get(date) ?? null })),
    },
    recordDays: new Set(perDay.keys()),
    summary: { alertsIssued: alerts },
  };
}

// Of n recipients, the seeder never reaches 1 in 17 on any channel; of the
// rest, about 1 in 9 push and 1 in 23 SMS sends fail, and 1 in 11 audible
// alerts is sent without being confirmed delivered.
const neverReached = (n) => Math.ceil(n / 17);

function channelOutcomes(n) {
  const never = neverReached(n);
  const rest = n - never;
  const missed = { PUSH: Math.round(rest / 9), SMS: Math.round(rest / 23), AUDIBLE: 0 };
  const unconfirmed = { PUSH: 0, SMS: 0, AUDIBLE: Math.round(rest / 11) };
  return CHANNELS.map((channel) => ({
    channel,
    attempted: n,
    delivered: rest - missed[channel] - unconfirmed[channel],
    failed: never + missed[channel],
  }));
}

const withRate = (row) => ({
  ...row,
  deliveryRate: row.attempted === 0 ? null : row.delivered / row.attempted,
});

function compileCitizensReached(ctx) {
  const firstAt = (alert) => alert.history.find((change) => ctx.inRange(change.at)).at;
  const alerts = alertsFor(ctx).sort(
    (a, b) => firstAt(a).localeCompare(firstAt(b)) || a.referenceNo.localeCompare(b.referenceNo),
  );

  // Every send in the range: one delivery record per recipient and channel.
  const sends = alerts.flatMap((alert) =>
    alert.history
      .filter((change) => ctx.inRange(change.at))
      .map((change) => ({
        alert,
        date: dayOf(change.at),
        outcomes: channelOutcomes(citizensIn(alert.districtIds)),
      })),
  );
  const sum = (rows) =>
    CHANNELS.map((channel) => {
      const ofChannel = rows.filter((row) => row.channel === channel);
      return {
        channel,
        attempted: ofChannel.reduce((total, row) => total + row.attempted, 0),
        delivered: ofChannel.reduce((total, row) => total + row.delivered, 0),
        failed: ofChannel.reduce((total, row) => total + row.failed, 0),
      };
    });

  const perDay = new Map();
  sends.forEach(({ date, outcomes }) => {
    const counts = perDay.get(date) ?? { attempted: 0, delivered: 0 };
    outcomes.forEach((row) => {
      counts.attempted += row.attempted;
      counts.delivered += row.delivered;
    });
    perDay.set(date, counts);
  });

  // Each citizen counts once, however many alerts and channels reached them.
  const targeted = citizensIn([...new Set(sends.flatMap(({ alert }) => alert.districtIds))]);
  const reached = targeted - neverReached(targeted);
  const reachedRate = targeted === 0 ? null : reached / targeted;
  return {
    result: {
      citizensReached: reached,
      citizensTargeted: targeted,
      reachedRate,
      perChannel: sum(sends.flatMap(({ outcomes }) => outcomes)).map(withRate),
      perAlert: alerts.map((alert) => {
        const recipients = citizensIn(alert.districtIds);
        return {
          alert: { id: alert.id, referenceNo: alert.referenceNo },
          citizensReached: recipients - neverReached(recipients),
          perChannel: sum(
            sends.filter((send) => send.alert === alert).flatMap(({ outcomes }) => outcomes),
          ).map(({ channel, attempted, delivered }) => ({ channel, attempted, delivered })),
        };
      }),
      days: ctx.days.map((date) => ({
        date,
        attempted: perDay.get(date)?.attempted ?? null,
        delivered: perDay.get(date)?.delivered ?? null,
      })),
    },
    recordDays: new Set(perDay.keys()),
    summary: { citizensReached: reached, citizensTargeted: targeted, reachedRate },
  };
}

// A district's occupancy at each moment is the sum of its shelters' latest
// occupants (a record from before the range gives the starting value); a
// day's peak is the highest of those sums that day.
function compileOccupancy(ctx) {
  const selected = OCCUPANCY_RECORDS.filter((record) => ctx.districtIds.includes(record.district));
  const latest = new Map(ctx.districtIds.map((id) => [id, new Map()]));
  const peaks = new Map(ctx.districtIds.map((id) => [id, new Map()]));

  selected
    .filter((record) => dayOf(record.recordedAt) < ctx.from)
    .sort((a, b) => a.recordedAt.localeCompare(b.recordedAt))
    .forEach((record) => latest.get(record.district).set(record.shelter, record.occupants));

  const moments = new Map();
  selected
    .filter((record) => ctx.inRange(record.recordedAt))
    .forEach((record) =>
      moments.set(record.recordedAt, [...(moments.get(record.recordedAt) ?? []), record]),
    );
  [...moments.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .forEach(([moment, records]) => {
      records.forEach((record) =>
        latest.get(record.district).set(record.shelter, record.occupants),
      );
      const day = dayOf(moment);
      new Set(records.map((record) => record.district)).forEach((district) => {
        const total = [...latest.get(district).values()].reduce((sum, value) => sum + value, 0);
        peaks.get(district).set(day, Math.max(peaks.get(district).get(day) ?? 0, total));
      });
    });

  const recordDays = new Set();
  const districts = ctx.districts.map((district) => {
    const dayPeaks = peaks.get(district.id);
    dayPeaks.forEach((_peak, day) => recordDays.add(day));
    let peak = null;
    ctx.days.forEach((date) => {
      if (dayPeaks.has(date) && (peak === null || dayPeaks.get(date) > peak.value)) {
        peak = { value: dayPeaks.get(date), date };
      }
    });
    return {
      district,
      days: ctx.days.map((date) => ({ date, peak: dayPeaks.get(date) ?? null })),
      peak,
    };
  });

  // The highest daily total across the districts; a tie goes to the earlier day.
  let summary = { peakOccupancy: null, peakOccupancyDate: null };
  ctx.days.forEach((date) => {
    const onDay = districts.map((row) => row.days.find((day) => day.date === date).peak);
    if (onDay.every((value) => value === null)) return;
    const total = onDay.reduce((sum, value) => sum + (value ?? 0), 0);
    if (summary.peakOccupancy === null || total > summary.peakOccupancy) {
      summary = { peakOccupancy: total, peakOccupancyDate: date };
    }
  });
  return { result: { districts }, recordDays, summary };
}

// Quantities by district x supply type x organisation, summed across units.
function compileDistribution(ctx) {
  const records = DISTRIBUTIONS.filter(
    (record) =>
      ctx.districtIds.includes(record.district) &&
      (ctx.organisationId === null || record.organisation.id === ctx.organisationId) &&
      ctx.inRange(record.distributedAt),
  );
  const rows = new Map();
  const perDay = new Map();
  records.forEach((record) => {
    const key = [record.district, record.supplyType, record.organisation.id].join('|');
    const row = rows.get(key) ?? {
      district: ctx.districts.find(({ id }) => id === record.district),
      supplyType: record.supplyType,
      organisation: record.organisation,
      quantity: 0,
    };
    row.quantity += record.quantity;
    rows.set(key, row);
    const day = dayOf(record.distributedAt);
    perDay.set(day, (perDay.get(day) ?? 0) + record.quantity);
  });

  const sorted = [...rows.values()].sort(
    (a, b) =>
      a.district.name.localeCompare(b.district.name) ||
      SUPPLY_TYPES.indexOf(a.supplyType) - SUPPLY_TYPES.indexOf(b.supplyType) ||
      a.organisation.name.localeCompare(b.organisation.name),
  );
  const total = sorted.reduce((sum, row) => sum + row.quantity, 0);
  return {
    result: {
      rows: sorted,
      total,
      days: ctx.days.map((date) => ({ date, quantity: perDay.get(date) ?? null })),
    },
    recordDays: new Set(perDay.keys()),
    summary: { itemsDistributed: total },
  };
}

// The A1 filters each section honours (§14.9), as on the server.
const SECTION_FILTERS = {
  alertTimeline: ['districtId', 'hazardType'],
  citizensReached: ['districtId', 'hazardType'],
  occupancyOverTime: ['districtId'],
  resourceDistribution: ['districtId', 'organisationId'],
};
const NO_FILTERS = { hazardType: null, districtId: null, organisationId: null };
const HAZARD_TYPES = ['FLOOD', 'LANDSLIDE', 'CYCLONE', 'DROUGHT'];

const COMPILERS = {
  alertTimeline: compileAlertTimeline,
  citizensReached: compileCitizensReached,
  occupancyOverTime: compileOccupancy,
  resourceDistribution: compileDistribution,
};

// Step 10: the days without records, consecutive days merged into one gap.
function gapsIn(section, days, recordDays) {
  const gaps = [];
  days.forEach((date, index) => {
    if (recordDays.has(date)) return;
    const last = gaps[gaps.length - 1];
    if (last && last.to === days[index - 1]) {
      last.to = date;
    } else {
      gaps.push({ section, from: date, to: date, reason: GAP_REASONS[section] });
    }
  });
  return gaps;
}

// The report object as the server returns it (§14.2). A district filter
// compiles every section for that one district; the hazard and organisation
// filters reach only the sections that honour them (A1, §14.9).
function buildReport(event, { from, to, districtIds, sections }, filters = NO_FILTERS) {
  const districts = event.districts.filter(({ id }) => districtIds.includes(id));
  const compiledFor = filters.districtId
    ? districts.filter(({ id }) => id === filters.districtId)
    : districts;
  const base = {
    event,
    from,
    to,
    districts: compiledFor,
    districtIds: compiledFor.map(({ id }) => id),
    days: daysBetween(from, to),
    inRange: (instant) => {
      const day = dayOf(instant);
      return day >= from && day <= to;
    },
  };
  const contextFor = (key) => ({
    ...base,
    hazardType: SECTION_FILTERS[key].includes('hazardType') ? filters.hazardType : null,
    organisationId: SECTION_FILTERS[key].includes('organisationId') ? filters.organisationId : null,
  });

  const summary = {
    alertsIssued: null,
    citizensReached: null,
    citizensTargeted: null,
    reachedRate: null,
    peakOccupancy: null,
    peakOccupancyDate: null,
    itemsDistributed: null,
  };
  const compiled = SECTION_KEYS.filter((key) => sections.includes(key)).map((key) => {
    const section = COMPILERS[key](contextFor(key));
    Object.assign(summary, section.summary);
    return { key, ...section };
  });

  // E2: no report when every requested section is empty.
  if (compiled.every(({ recordDays }) => recordDays.size === 0)) {
    throw apiError(404, 'NO_DATA_FOR_SELECTION', 'No data is available for this selection.');
  }

  const gaps = compiled.flatMap(({ key, recordDays }) => gapsIn(key, base.days, recordDays));
  const generatedAt = new Date().toISOString();
  return {
    id: `66fc4a1b2c3d4e5f6a7b${(0x9e00 + nextReport++).toString(16)}`,
    event: {
      id: event.id,
      name: event.name,
      hazardType: event.hazardType,
      startDate: event.startDate,
      endDate: event.endDate,
    },
    generatedBy: OFFICER,
    generatedAt,
    dateFrom: from,
    dateTo: to,
    districts,
    filters: { ...filters },
    summary,
    hasGaps: gaps.length > 0,
    gaps,
    sections: compiled.map(({ key, result }) => ({ key, result })),
    createdAt: generatedAt,
  };
}

const copy = (value) => JSON.parse(JSON.stringify(value));

// --- The API ---

async function listClosedEvents() {
  await delay();
  takeFailure();
  return EVENTS.filter((event) => event.status === 'CLOSED')
    .sort((a, b) => b.startDate.localeCompare(a.startDate))
    .map(copy);
}

async function generate(params = {}) {
  await delay();
  takeFailure();
  const errors = shapeErrors(params);
  if (errors.length > 0) throw validationError(errors);

  const event = EVENTS.find(({ id }) => id === params.eventId);
  if (!event) throw apiError(404, 'NOT_FOUND', 'Hazard event not found.');
  takeFailure({ generating: true });
  if (event.status !== 'CLOSED') {
    throw apiError(
      409,
      'EVENT_NOT_CLOSED',
      `A report can only be generated for a CLOSED event – current status: ${event.status}`,
    );
  }
  const problems = parameterErrors(event, params);
  if (problems.length > 0) throw validationError(problems);

  const report = buildReport(event, params);
  reports.set(report.id, report);
  return copy(report);
}

async function getReport(id) {
  await delay();
  takeFailure();
  const report = reports.get(id);
  if (!report) throw apiError(404, 'NOT_FOUND', 'Post-event report not found.');
  return copy(report);
}

async function listRecent(eventId) {
  await delay();
  takeFailure();
  if (!isId(eventId)) {
    throw validationError([
      {
        field: 'eventId',
        message: eventId === undefined ? 'eventId is required' : 'must be a valid id',
      },
    ]);
  }
  return [...reports.values()]
    .filter((report) => report.event.id === eventId)
    .sort((a, b) => b.generatedAt.localeCompare(a.generatedAt) || b.id.localeCompare(a.id))
    .slice(0, RECENT_LIMIT)
    .map((report) => copy(listItem(report)));
}

// The refine body's shape and the report-specific rules, in the server's
// order (§14.9): a bad shape first, then no filter set, then a district the
// report doesn't cover.
function filterErrors(report, filters) {
  const errors = [];
  const { hazardType = null, districtId = null, organisationId = null } = filters;
  if (hazardType !== null && !HAZARD_TYPES.includes(hazardType)) {
    errors.push({ field: 'hazardType', message: `must be one of [${HAZARD_TYPES.join(', ')}]` });
  }
  if (districtId !== null && !isId(districtId)) {
    errors.push({ field: 'districtId', message: 'must be a valid id' });
  }
  if (organisationId !== null && !isId(organisationId)) {
    errors.push({ field: 'organisationId', message: 'must be a valid id' });
  }
  if (errors.length > 0) return errors;
  if (hazardType === null && districtId === null && organisationId === null) {
    return [{ field: 'filters', message: 'must set at least one filter' }];
  }
  if (districtId !== null && !report.districts.some(({ id }) => id === districtId)) {
    return [{ field: 'districtId', message: "must be one of the report's districts" }];
  }
  return [];
}

async function refine(id, filters = {}) {
  await delay();
  takeFailure();
  const source = reports.get(id);
  if (!source) throw apiError(404, 'NOT_FOUND', 'Post-event report not found.');
  const errors = filterErrors(source, filters);
  if (errors.length > 0) throw validationError(errors);
  const wanted = { ...NO_FILTERS, ...filters };
  if (
    wanted.organisationId !== null &&
    !ALL_ORGANISATIONS.some(({ id: orgId }) => orgId === wanted.organisationId)
  ) {
    throw apiError(404, 'NOT_FOUND', 'Organisation not found.');
  }

  const event = EVENTS.find(({ id: eventId }) => eventId === source.event.id);
  const report = buildReport(
    event,
    {
      from: source.dateFrom,
      to: source.dateTo,
      districtIds: source.districts.map(({ id: districtId }) => districtId),
      sections: source.sections.map(({ key }) => key),
    },
    wanted,
  );
  reports.set(report.id, report);
  return copy(report);
}

async function listOrganisations() {
  await delay();
  takeFailure();
  return ALL_ORGANISATIONS.map(copy);
}

// A report without its summary, gaps and sections (§14.5).
function listItem(report) {
  return {
    id: report.id,
    event: { id: report.event.id, name: report.event.name },
    generatedBy: report.generatedBy,
    generatedAt: report.generatedAt,
    dateFrom: report.dateFrom,
    dateTo: report.dateTo,
    districts: report.districts,
    filters: report.filters,
    hasGaps: report.hasGaps,
  };
}

/**
 * Demo hooks, not part of the API: `failNext('network')` makes the next call
 * fail as if offline, `failNext('server')` answers it with a 500, and
 * `failNext('notClosed')` answers the next generate with 409 EVENT_NOT_CLOSED.
 */
export const mockControls = {
  failNext(kind) {
    pendingFailure = kind;
  },
};

export default {
  listClosedEvents,
  generate,
  getReport,
  listRecent,
  refine,
  listOrganisations,
};
